name: Validate MCPB Manifest
description: Validate manifest.json before packing

inputs:
  strict:
    description: "Treat warnings as errors"
    default: "false"
  working-directory:
    description: "Directory containing manifest.json"
    default: "."

outputs:
  valid:
    description: "Whether validation passed"
    value: ${{ steps.validate.outputs.valid }}

runs:
  using: composite
  steps:
    - name: Validate tool-cli is installed
      shell: bash
      run: |
        if ! command -v tool &>/dev/null; then
          echo "::error::tool-cli is not installed. Use zerocore-ai/tool-action/setup first."
          exit 1
        fi

    - name: Validate manifest
      id: validate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail

        # Check manifest.json exists
        if [ ! -f "manifest.json" ]; then
          echo "::error::manifest.json not found in ${{ inputs.working-directory }}"
          exit 1
        fi

        # Build validation command
        ARGS="validate"
        if [ "${{ inputs.strict }}" = "true" ]; then
          ARGS="$ARGS --strict"
        fi

        echo "Running: tool $ARGS"

        # Run validation
        if tool $ARGS; then
          echo "valid=true" >> "$GITHUB_OUTPUT"
          echo "Validation passed"
        else
          echo "valid=false" >> "$GITHUB_OUTPUT"
          echo "::error::Validation failed"
          exit 1
        fi
