name: Setup tool-cli
description: Install tool-cli for building and publishing MCPB bundles

inputs:
  version:
    description: "tool-cli git tag to install (use 'latest' for main branch HEAD)"
    default: "latest"

outputs:
  version:
    description: "Installed tool-cli version"
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Restore cached tool-cli
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/tool
          ~/.cargo/bin/tool.exe
        key: tool-cli-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Setup Rust
      if: steps.cache.outputs.cache-hit != 'true'
      uses: dtolnay/rust-toolchain@stable

    - name: Install tool-cli
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          cargo install --git "https://github.com/zerocore-ai/tool-cli" --locked --force
        else
          cargo install --git "https://github.com/zerocore-ai/tool-cli" --tag "${{ inputs.version }}" --locked --force
        fi

    - name: Add to PATH
      shell: bash
      run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

    - name: Verify installation
      id: version
      shell: bash
      run: |
        VERSION="$(tool --version)"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "Installed: $VERSION"
